# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
LIBO="/home/libo/my/git/david/i_libo"
TOOL="${LIBO}/env/tool"

PATH=$HOME/bin:$TOOL/bash:$TOOL/php:$LIBO:$PATH:/usr/sbin
export PATH
unset USERNAME

PS1="[\u@\h \W]\$ "
export PS1

# translate into chinese
#export LANG=zh_CN.utf8
export EDITOR=vim
