#!/bin/bash

ENV="/root/git/sunshine/env"

cd $HOME

rm .bash_profile
ln -s $ENV/.bash_profile .bash_profile

rm .bashrc
ln -s $ENV/.bashrc .bashrc

rm .git-completion.bash
ln -s $ENV/.git-completion.bash .git-completion.bash

rm .gitconfig
ln -s $ENV/.gitconfig .gitconfig

rm .vimrc
ln -s $ENV/.vimrc .vimrc

rm yum-list
ln -s $ENV/yum-list yum-list
