#!/bin/bash

ENV="/root/git/sunshine/env"

cd $HOME

rm .bash_profile
ln -s $ENV/.bash_profile .bash_profile

rm .bashrc
ln -s $ENV/.bashrc .bashrc

rm .git-completion.bash
ln -s $ENV/.git-completion.bash .git-completion.bash

rm .gitconfig
ln -s $ENV/.gitconfig .gitconfig

rm .vimrc
ln -s $ENV/.vimrc .vimrc

rm /usr/local/bin/php
ln -s /usr/local/eyou/mail/opt/bin/php /usr/local/bin/php 
